#!/bin/sh


# build and run fortran unit tests
dir="./nn/fortran/"

cd $dir

unittest="./build_unittest.sh"

echo "evaluating "$unittest" from "
pwd
ls
$unittest

ret_status=$?

if [ $ret_status == 1 ]; then
    # SUCCESS
    exit 0
else
    # FAILURE
    exit 1
fi
